onboarding = false

[theme]
name = "catppuccin"
auto_switch = false

[ui]
prompt_new_tab_name = false

[ui.sound]
enabled = false

[ui.toast]
delivery = "herdr"

[keys]
prefix = "ctrl+a"
focus_pane_left = "alt+shift+h"
focus_pane_down = "alt+shift+j"
focus_pane_up = "alt+shift+k"
focus_pane_right = "alt+shift+l"
previous_tab = "alt+left"
next_tab = "alt+right"

[experimental]
pane_history = true
