onboarding = false
[ui]
agent_panel_scope = "all"
prompt_new_tab_name = false

[theme]
name = "nord"

[ui.sound]
enabled = false

[keys]
prefix = "ctrl+a"
focus_pane_left = "alt+shift+h"
focus_pane_down = "alt+shift+j"
focus_pane_up = "alt+shift+k"
focus_pane_right = "alt+shift+l"
previous_tab = "alt+left"
next_tab = "alt+right"

[ui.toast]
delivery = "herdr"

[experimental]
pane_history = true
