# helix

theme = "nord-night"

[editor]
clipboard-provider = "wayland"
scrolloff = 999
line-number = "relative"
bufferline = "always"
trim-trailing-whitespace = true # Trim whitespace preceding line endings on write (default false)
trim-final-newlines = true # Trim extra line endings after the final one on write (default false)

[editor.auto-save]
focus-lost = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"
