# helix

theme = "nord-night"

[editor]
bufferline = "always"
clipboard-provider = "wayland"
cursorline = true
default-yank-register = "+"
line-number = "relative"
scrolloff = 999
trim-trailing-whitespace = true # Trim whitespace preceding line endings on write (default false)
trim-final-newlines = true # Trim extra line endings after the final one on write (default false)
true-color = true

[editor.auto-save]
focus-lost = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
C-s = ":write"
C-w = ":write-buffer-close"

[keys.normal]
C-r = ":config-reload"
C-s = ":write"
C-w = ":write-buffer-close"

[keys.select]
C-s = ":write"
C-w = ":write-buffer-close"
