## ZSH configuration

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.antigen/bundles/robbyrussell/oh-my-zsh/"

# Append history
setopt incappendhistory

# Update PATH
export PATH=$HOME/.local/bin:$PATH

## OMZSH configuration

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
UPDATE_ZSH_DAYS=7

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="dd.mm.yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM="$HOME/.zsh"

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.zsh/custom/plugins/
plugins=(
)

# OMZ
source $ZSH/oh-my-zsh.sh

# Antigen plugins manager
ANTIGEN_ZSH="/usr/share/zsh-antigen/antigen.zsh"
source $ANTIGEN_ZSH
antigen init ~/.antigenrc

## User configuration

# Completion
autoload -Uz compinit
zstyle ':completion:*' menu select
fpath+=~/.zfunc

# PyEnv
if (( $+commands[pyenv] )); then
    export PYENV_VIRTUALENV_DISABLE_PROMPT=1
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi

# Golang
if [ -d "${HOME}/go/bin" ]; then
    PATH="${HOME}/go/bin:${HOME}/go/packages/bin${PATH:+:${PATH}}"; export PATH;
    export GOROOT="${HOME}/go"
    export GOPATH="${HOME}/go/packages"
    export GOBIN="${GOPATH}/bin"
    export GOARCH=amd64
    export GOOS=linux
fi

# GNOME Keyring
export SSH_AUTH_SOCK="/run/user/$UID/keyring/ssh"

# Keychain
# if (( $+commands[keychain] )); then
#     eval "$(keychain -q --eval)"
# fi

# Local RC file
[ -s "$HOME/.zshrc.local" ] && . "$HOME/.zshrc.local"
